### ISSUE TITLE
PromoRequest should include page_type 

### ISSUE THREAD

**Issue by diptib10** [Affirm/affirm-merchant-sdk-android#13]
Ex: https://sandbox.affirm.com/api/promos/v2/MJQ0B6BEVJDPS0YG?field=ala&amount=50000&logo_color=blue&logo_type=logo&page_type=product&promo_external_id=promo_set_default_product&show_cta=true

Should be an optional field.

**Comment by wangdaliu** [comment]
https://github.com/Affirm/affirm-merchant-sdk-android/pull/14
