### ISSUE TITLE
Price amount is not in cents

### ISSUE THREAD

**Issue by nandadubey** [Affirm/affirm-merchant-sdk-android#3]
As the price amount (and other amounts shipping and tax) in all functions is not in cents, due to that prequal screen is showing incorrect amount. Though it shows correct amount in ala message but internally when processed for prequal it takes 500 as $5 amount (screenshot attached). Affirm api and prequal docs all provides guideline to use amount in USD cents (e.g., $100 = 10000) so I think it will be good to keep that consistent in SDK also. https://docs.affirm.com/Integrate_Affirm/Monthly_Payment_Messaging
<img width="262" alt="Screen Shot 2019-04-18 at 7 08 06 PM" src="https://user-images.githubusercontent.com/29716662/56401453-bc9ccb80-620d-11e9-8232-f91ceb8b8184.png">
<img width="261" alt="Screen Shot 2019-04-18 at 7 08 29 PM" src="https://user-images.githubusercontent.com/29716662/56401454-bc9ccb80-620d-11e9-9634-e70c318e2059.png">

**Comment by wangdaliu** [comment]
https://github.com/Affirm/affirm-merchant-sdk-android/pull/4
