### ISSUE TITLE
Logo type text is not appearing

### ISSUE THREAD

**Issue by AmyBeall** [Affirm/affirm-merchant-sdk-android#35]
Please see the following examples:
` affirmPromotionButton1.configWithLocalStyling(
                AffirmColor.AFFIRM_COLOR_TYPE_BLUE,
                AffirmLogoType.AFFIRM_DISPLAY_TYPE_TEXT,
                ResourcesCompat.getFont(this, R.font.atlantic_time),
                android.R.color.darker_gray,
                R.dimen.affirm_promotion_size);`
![image](https://user-images.githubusercontent.com/8650185/62397088-ac44fe00-b529-11e9-8ae9-b992d45bd690.png)
` affirmPromotionButton1.configWithLocalStyling(
                AffirmColor.AFFIRM_COLOR_TYPE_BLUE,
                AffirmLogoType.AFFIRM_DISPLAY_TYPE_TEXT);`
![image](https://user-images.githubusercontent.com/8650185/62397152-d0a0da80-b529-11e9-8237-3f99e9bc3153.png)

**Comment by wangdaliu** [comment]
@AmyBeall Fixed https://github.com/Affirm/affirm-merchant-sdk-android/pull/36

**Comment by AmyBeall** [comment]
Thanks!
